name: Build and Push Docker Image
on:
  push:
    branches: [master]
    tags: ["v*"]

permissions:
  contents: write

jobs:
  go-functions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy Function
        id: sls-func
        uses: yc-actions/yc-sls-function@v4
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
          folder-id: 'b1gu6ki730mglrb8c54t'
          function-name: 'mmm'
          runtime: 'golang123'
          networkId: 'enp0a07mf9e1o23ktfs9'
          memory: '128Mb'
          entrypoint: 'cmd/mmm/index.Handler'
          include: |
            ./cmd/mmm
            ./src
            ./go.mod
            ./go.sum
          log-level: debug
  web:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '25'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Lint and Type-check
        run: |
          yarn lint
          yarn type-check

      - name: Build project
        run: yarn build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
