name: Build and Push Docker Image
on:
  push:
    branches: [master]
    tags: ["v*"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy Function
        id: sls-func
        uses: yc-actions/yc-sls-function@v4
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
          folder-id: 'b1gu6ki730mglrb8c54t'
          function-name: 'mmm'
          runtime: 'golang123'
          memory: '128Mb'
          entrypoint: 'src/mmm/index.handler'
          include: |
            ./cmd/mmm
            ./src
            ./go.mod
            ./go.sum